package asg.games.yokel.enums;

public enum ServerRequest {
    REQUEST_ALL_DEBUG_PLAYERS("REQUEST_ALL_DEBUG_PLAYERS"),
    REQUEST_ALL_REGISTERED_PLAYERS("REQUEST_ALL_REGISTERED_PLAYERS"),
    REQUEST_LOGOFF("REQUEST_LOGOFF"),
    REQUEST_PLAYER_REGISTER("REQUEST_PLAYER_REGISTER"),
    REQUEST_CREATE_GAME("REQUEST_CREATE_GAME"),
    REQUEST_PLAY_GAME("REQUEST_PLAY_GAME"),
    REQUEST_TABLE_STAND("REQUEST_TABLE_STAND"),
    REQUEST_TABLE_JOIN("REQUEST_TABLE_JOIN"),
    REQUEST_TABLE_SIT("REQUEST_TABLE_SIT"),
    REQUEST_ROOM("REQUEST_ROOM"),
    REQUEST_ROOM_JOIN("REQUEST_ROOM_JOIN"),
    REQUEST_ROOM_LEAVE("REQUEST_ROOM_LEAVE"),
    REQUEST_LOUNGE("REQUEST_LOUNGE"),
    REQUEST_TABLE_INFO("REQUEST_TABLE_INFO"),
    REQUEST_LOUNGE_ALL("REQUEST_LOUNGE_ALL"),
    REQUEST_CLIENT_ID("REQUEST_CLIENT_ID"),
    REQUEST_CLIENT_DISCONNECT("REQUEST_CLIENT_DISCONNECT"),
    REQUEST_EMPTY("REQUEST_EMPTY"),
    REQUEST_TABLE_GAME_MANAGER("REQUEST_TABLE_GAME_MANAGER"),
    REQUEST_TABLE_MOVE_RIGHT("REQUEST_TABLE_MOVE_RIGHT"),
    REQUEST_TABLE_MOVE_LEFT("REQUEST_TABLE_MOVE_LEFT"),
    REQUEST_TABLE_CYCLE_UP("REQUEST_TABLE_CYCLE_UP"),
    REQUEST_TABLE_CYCLE_DOWN("REQUEST_TABLE_CYCLE_DOWN"),
    REQUEST_TABLE_MOVE_START_DOWN("REQUEST_TABLE_MOVE_START_DOWN"),
    REQUEST_TABLE_MOVE_STOP_DOWN("REQUEST_TABLE_MOVE_STOP_DOWN"),
    REQUEST_TABLE_ATTACK_RANDOM("REQUEST_TABLE_ATTACK_RANDOM"),
    REQUEST_TABLE_ATTACK_TARGET("REQUEST_TABLE_ATTACK_TARGET");

    private String requestType;

    ServerRequest(String type){
        this.requestType = type;
    }

    public String getValue() {
        return requestType;
    }
}